version: '3.8'

services:
  app:
    build: .
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    volumes:
      - models_data:/app/models
      - cache_data:/app/cache
      - documents_data:/app/documents
    ports:
      - "5000:5000"
    entrypoint: ["/app/entrypoint.sh"]
    restart: unless-stopped

volumes:
  models_data:
  cache_data:
  documents_data: